api/urls.py
from collections import UserList
from django.urls import path, include
from .views import UserProfileView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/users/profile/', UserProfileView.as_view(), name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'), name='users'),
    path('', include('main.urls'), name='main'),
    path('', include('attendance.urls'), name='attendance'),
    path('', include('students.urls'), name='students'),
    path('', include('courses.urls'), name='courses'),
    path('', include('payment.urls'), name='payment'),
    path('', include('leads.urls'), name='leads'),
    path('', include('analytics.urls'), name='analytics'),

    path('api-auth/', include('rest_framework.urls')),
    # path('', include('api.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

from .views import CustomUserCreateView, reset_user_password, UserUpdateView, LoginPageView, ProfileView, TeacherUpdateView, CustomPasswordChangeView, SalaryUsersListView, SalaryCourseDetailView, AdminActionsView, UsersListView

# Api
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import UserProfileView
app_name = 'users'

urlpatterns = [
    path('login/', LoginPageView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('home')), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('teacher/<int:pk>', TeacherUpdateView.as_view(), name='teacher_update'),
    path('profile/password-change/', CustomPasswordChangeView.as_view(), name='update_password'),
    path('actions-history/', AdminActionsView.as_view(), name='admin_actions'),

    path('users/', UsersListView.as_view(), name='users_list'),
    path('users/<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('users/<int:pk>/reset-password/', reset_user_password, name='reset_user_password'),
    path('users/create/', CustomUserCreateView.as_view(), name='user_create'),
    path('salary/users/', SalaryUsersListView.as_view(), name='salary_users_list'),
    path('salary/teacher/<int:teacher_id>/course/<int:course_id>', SalaryCourseDetailView.as_view(), name='salary_course_detail'),


    #     API
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/users/profile/', UserProfileView.as_view(), name='user-profile'),
]

users/models.py
from random import choices
import os
from datetime import datetime, timedelta
from django.db import models
from django.contrib.auth.models import AbstractUser, User
from django.contrib.admin.models import LogEntry, ContentType
from django.apps import apps
from PIL import Image, ImageOps
from requests import session

PERMISSION_CHOICES = [
    ('delete_enrollment', 'Может удалить ученика из группы'),
    ('re_enrollment', 'Может перемещать запись'),
    ('mark_session', 'Может отмечать уроки (только во время урока)'),
    ('change_attendance', 'Может изменить посещаемость'),
    ('create_payment', 'Может вводить оплату'),
]

def get_default_permissions():
    return [perm[0] for perm in PERMISSION_CHOICES]

def convert_file_name(instance, filename):
    ext = filename.split('.')[-1]
    filename = '{:%Y-%m-%d-%H-%M-%S-%f}.{}'.format(datetime.now(), ext)
    return os.path.join('./users', filename)

class UsersModel(AbstractUser):
    ROLE_CHOICES = [
        ('1', 'Учитель'),
        ('2', 'Администратор'),
    ]
    image = models.ImageField(upload_to=convert_file_name, null=True, blank=True)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='1', verbose_name='Роль')
    phone_number = models.CharField(max_length=13, null=True, blank=True, verbose_name="Номер Телефона")
    bio = models.TextField(null=True, blank=True, verbose_name='Биография')
    color = models.CharField(max_length=7, default='#ffffff', null=True, blank=True, verbose_name="Цвет выделения")
    custom_permissions = models.JSONField(default=get_default_permissions, blank=True, null=True)
    display_in_bot = models.BooleanField(default=True, verbose_name="Показать в боте")

    def has_permission(self, permission):
        return permission in self.custom_permissions

    # Store selected permissions as a set of boolean flags
    @property
    def get_full_name(self) -> str:
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"
        elif self.first_name or self.last_name:
            return self.first_name or self.last_name
        else:
            return self.username

    @property
    def get_short_name(self) -> str:
        if self.first_name and self.last_name:
            return f"{self.first_name[0]}. {self.last_name}"
        elif self.first_name or self.last_name:
            return self.first_name or self.last_name
        else:
            return self.username

    def __str__(self):
        return f"{self.get_full_name} - {self.username}"

    def get_courses(self):
        Courses = apps.get_model('courses', 'CourseModel')
        filter = Courses.objects.filter(teacher=self).order_by('subject', 'weekdays','lesson_time')
        return filter

    def get_sessions_courses(self):
        Courses = apps.get_model('courses', 'CourseModel')
        Sessions = apps.get_model('courses', 'SessionsModel')

        dt = datetime.now() - timedelta(weeks=8)
        sessions = Sessions.objects.filter(date__gte=dt, course__teacher=self).values_list('course', flat=True)
        courses = Courses.objects.filter(id__in=sessions)

        course_sessions = Sessions.objects.filter(record_by=self, date__gte=dt).values_list('course', flat=True)
        if course_sessions.count() > 0:
            additional_courses = Courses.objects.filter(id__in=course_sessions)
            courses = courses.union(additional_courses)

        return courses

    def get_enrollments(self):
        Enrollments = apps.get_model('students', 'Enrollment')
        courses = self.get_courses()
        filter = Enrollments.objects.filter(course__in=courses, status=True, trial_lesson=False)
        return filter

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # first save the original

        if self.image:
            img_path = self.image.path
            img = Image.open(img_path)
            # Fix rotation according to EXIF
            img = ImageOps.exif_transpose(img)
            # Example: Resize to max 300x300
            max_size = (800, 800)
            img.thumbnail(max_size)  # keeps aspect ratio
            img.save(img_path, format='JPEG', quality=85, optimize=True)

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'


def log_user_action(user, obj, action_flag, message):
    LogEntry.objects.log_action(
        user_id=user.id,
        content_type_id=ContentType.objects.get_for_model(obj).pk,
        object_id=obj.pk,
        object_repr=str(obj),
        action_flag=action_flag,
        change_message=message
    )

ACTION_FLAG_CHOICES = [
    (1, "Создать"),
    (2, "Изменить"),
    (3, "Удалить"),
]

class LogAdminActionsModel(models.Model):
    action_number = models.PositiveSmallIntegerField(choices=ACTION_FLAG_CHOICES)
    user = models.ForeignKey(UsersModel, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    message = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)

    def action_type(self):
        return self.get_action_number_display()

    def __str__(self):
        return  f"{self.user.username} - {self.content_type.name} - {self.action_number}"

    class Meta:
        verbose_name = 'запись'
        verbose_name_plural = 'записи'


class TelegramChatsModel(models.Model):
    name = models.CharField(max_length=200)
    chat_id = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name} - {self.chat_id}"

templates/users/user_create.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <title>Панель Управления</title>
{% endblock %}
{% block content %}
    {% include 'layout/navbar.html' %}

    <div class="container courses-list">

        <h4 class="mt-5">Создать нового пользователя</h4>
        <hr class="table-group-divider"/>
        <div class="bg-light rounded py-3 mt-3 px-2 border">

            <form method="post">
                <div>
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'custom_permissions' %}
                            {% if field.name != 'is_active' %}

                                <div class="form-floating my-1">
                                    {{ field }}
                                    <label aria-required="{{ field.field.required }}" {{ field.required }}
                                           for="{{ field.id_for_label }}">{{ field.label }}</label>
                                </div>

                            {% else %}
                                <div class="d-flex align-items-center my-1 ms-1 mt-2 gap-2">
                                    {{ field }}
                                    <label aria-required="{{ field.field.required }}" {{ field.required }}
                                           for="{{ field.id_for_label }}">{{ field.label }}</label>
                                </div>

                            {% endif %}
                        {% endif %}
                        {% if field.errors %}
                            <div class="text-danger small">
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div class="d-flex gap-2 ms-1 mt-2 align-items-center">
                        <input type="checkbox" id="showPassword"
                               class="form-check-input cursor-pointer border-2 fs-5 m-0">
                        <label for="showPassword" class="user-select-none cursor-pointer">Показать
                            пароли</label>
                    </div>
                    <div id="permissions-wrapper" class="d-none">
                        <a class="btn dropdown-toggle border-0 text-decoration-underline m-0 p-0 ps-2 py-2 mt-2"
                           data-bs-toggle="collapse" href="#permissionsCollapse" role="button"
                           aria-expanded="false" aria-controls="permissionsCollapse">
                            Разрешения
                        </a>
                        <div class="collapse show" id="permissionsCollapse">
                            <div class="card card-body">
                                {% for field in form.custom_permissions %}
                                    <div class="form-check">
                                        {{ field }}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="d-flex justify-content-end flex-column flex-md-row pt-3 gap-3">
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block custom_js %}
    <script defer>
        let showPasswordInp = document.getElementById('showPassword')

        showPasswordInp.addEventListener('click', (e) => {
            let passwordInps = document.querySelectorAll('.passwordinput')
            let status = e.target.checked
            passwordInps.forEach((inp) => {
                inp.type = status ? 'text' : 'password';
            })

        })

        function roleChange(select){
            let permissionWrapper = document.getElementById('permissions-wrapper')
            if (select.value == 2){
                permissionWrapper.classList.remove('d-none')
            }else{
                permissionWrapper.classList.add('d-none')
            }
        }
    </script>
{% endblock %}

templates/users/users_list.html
{% extends 'layout/base.html' %}

{% block title %}
    <title>Панель Управления</title>
{% endblock %}
{% block content %}
    {% include 'layout/navbar.html' %}

    <div class="container pt-1">
        <div class="mt-4 mb-2 d-flex align-items-center justify-content-between">
            <h5 class="m-0">Пользователи</h5>
            <div>
                <a href="{% url 'users:user_create' %}" type="button" class="btn btn-primary">
                    Создать
                </a>
            </div>
        </div>
        <hr class="table-group-divider"/>
        <div class="row m-0 p-0 ">
            <div class="col-12 bg-light rounded pt-2 px-2 border">
                <form id="filterForm" method="get" action="{% url 'users:users_list' %}" class=""
                      onreset="resetForm(event)">
                    <div class="">
                        <h6 class="text-dark  ms-1 fs-6 m-0">Фильтры
                            <button type="reset" class="filter-reset-btn ms-2 mb-1"><p>Очистить</p></button>
                        </h6>
                    </div>
                    <div class="row mt-2 pb-3">
                        <div class="col-12 col-md-6">
                            <div class="custom-select-2">
                                <label for="daySelect" class="me-2 ms-1 mb-1">{{ filter_form.text.label }}</label>
                                {{ filter_form.text }}
                            </div>
                        </div>
                        <div class="col-12 col-md-3">
                            <div class="custom-select-2">
                                <label for="daySelect" class="me-2 ms-1 mb-1">{{ filter_form.role.label }}</label>
                                {{ filter_form.role }}
                            </div>
                        </div>
                        <div class="col-12 col-md-3">
                            <div class="custom-select-2">
                                <label for="daySelect" class="me-2 ms-1 mb-1">{{ filter_form.status.label }}</label>
                                {{ filter_form.status }}
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row px-3 mt-3">
            <table class="table-bordered w-100">
                <thead>
                <tr>
                    <th class="w-auto"></th>
                    <th class="text-center w-auto">Имя пользователя</th>
                    <th class="text-center w-auto">Имя Фамилия</th>
                    <th class="text-center w-auto">Роль</th>
                    <th class="text-center">Статус</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr class="list-items-hover">
                        <td class="text-center">{{ user.id }}</td>
                        <td class="p-2"><a href="{% url 'users:user_update' pk=user.id %}"
                                           class="link-primary">{{ user.username }}</a></td>
                        <td class="p-2">{{ user.get_full_name }}</td>
                        <td class="p-2">{{ user.get_role_display }}</td>
                        <td class="p-2 text-center">
                            {% if user.is_active %}
                                <span class="badge text-bg-success p-1"><i class="bi bi-check-lg"></i></span>
                            {% else %}
                                <span class="badge text-bg-danger p-1"><i class="bi bi-x-lg"></i></span>
                            {% endif %}
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td class="text-center py-2" colspan="5">Пусто</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

            {% if page_obj.paginator.count > 30 %}
                {% include 'layout/pagination.html' %}
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/users/users_update.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <title>Панель Управления</title>
{% endblock %}
{% block content %}
    {% include 'layout/navbar.html' %}

    <div class="container courses-list">

        <h4 class="mt-5">Пользователь - <span class="text-primary">{{ obj_user.username }}</span>
            {% if obj_user.is_superuser %}<span class="text-secondary fs-6"> - супер админ</span>{% endif %}</h4>
        <hr class="table-group-divider"/>
        <div class="bg-light rounded py-3 mt-3 px-2 border">
            <form method="post">
                <div>
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.name != 'custom_permissions' %}
                            {% if field.name not in 'is_active' %}

                                <div class="form-floating my-1">
                                    {{ field }}
                                    <label aria-required="{{ field.field.required }}" {{ field.required }}
                                           for="{{ field.id_for_label }}">{{ field.label }}</label>
                                </div>

                            {% else %}
                                <div class="d-flex align-items-center my-1 ms-1 mt-2 gap-2">
                                    {{ field }}
                                    <label aria-required="{{ field.field.required }}" {{ field.required }}
                                           for="{{ field.id_for_label }}">{{ field.label }}</label>
                                </div>

                            {% endif %}
                        {% endif %}
                        {% if field.errors %}
                            <div class="text-danger small">
                                {% for error in field.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    {% endfor %}
                    {% if obj_user.role == '2' and not obj_user.is_superuser %}
                        <a class="btn dropdown-toggle border-0 text-decoration-underline m-0 p-0 ps-2 py-2 mt-2"
                           data-bs-toggle="collapse" href="#permissionsCollapse" role="button"
                           aria-expanded="false" aria-controls="permissionsCollapse">
                            Разрешения
                        </a>
                        <div class="collapse" id="permissionsCollapse">
                            <div class="card card-body">
                                {% for field in form.custom_permissions %}
                                    <div class="form-check">
                                        {{ field }}
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                    <div class="d-flex justify-content-end flex-column flex-md-row pt-3 gap-3">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                                data-bs-target="#passwordResetModal">
                            Сбросить пароль
                        </button>
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </div>
                </div>
            </form>
            <!-- Modal -->
            <div class="modal fade" id="passwordResetModal" data-bs-backdrop="static" data-bs-keyboard="false"
                 tabindex="-1"
                 aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <form method="post" action="{% url 'users:reset_user_password' object.pk %}">
                        {% csrf_token %}
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="staticBackdropLabel">Сбросить пароль</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                {{ password_form }}
                                <div class="d-flex gap-2 mt-3 align-items-center">
                                    <input type="checkbox" id="showPassword"
                                           class="form-check-input cursor-pointer border-2 fs-5 m-0">
                                    <label for="showPassword" class="user-select-none cursor-pointer">Показать
                                        пароли</label>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отменить
                                </button>
                                <button type="submit" class="btn btn-primary">Сбросить</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block custom_js %}
    <script defer>
        let showPasswordInp = document.getElementById('showPassword')

        showPasswordInp.addEventListener('click', (e) => {
            let passwordInps = document.querySelectorAll('.passwordinput')
            let status = e.target.checked
            passwordInps.forEach((inp) => {
                inp.type = status ? 'text' : 'password';
            })

        })
    </script>
{% endblock %}