api/urls.py
from collections import UserList
from django.urls import path, include
from .views import UserProfileView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/users/profile/', UserProfileView.as_view(), name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'), name='users'),
    path('', include('main.urls'), name='main'),
    path('', include('attendance.urls'), name='attendance'),
    path('', include('students.urls'), name='students'),
    path('', include('courses.urls'), name='courses'),
    path('', include('payment.urls'), name='payment'),
    path('', include('leads.urls'), name='leads'),
    path('', include('analytics.urls'), name='analytics'),

    path('api-auth/', include('rest_framework.urls')),
    # path('', include('api.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/urls.py
from django.urls import path

from .views import PaymentsListView, CreatePaymentView, DebtPaymentsListView, TrialEnrollmentsView, UpdatePaymentDatesView

app_name = 'payment'

urlpatterns = [
    # path('payments/', PaymentsListView.as_view(), name='payments_list'),
    # path('payments/debt', DebtPaymentsListView.as_view(), name='debt_payments_list'),
    # path('payments/trials', TrialEnrollmentsView.as_view(), name='trial_enrollments_list'),
    # path('payments/create/enrollment/<int:enrollment_id>', CreatePaymentView.as_view(), name='create_payment_enrollment'),
    # path('payment/<int:pk>/update/', UpdatePaymentDatesView.as_view(), name='update_payment_dates'),
]

students/urls.py
from django.urls import path
from .views import StudentUpdateView, CreateStudentView, CreateEnrollmentView, UpdateEnrollmentView, \
    GroupReEnrollmentView, DeactivateEnrollmentView, UpdateEnrollmentNote, ReEnrollStudentView, autocomplete_students, \
    ArchiveStudent, UnArchiveStudent, ConvertEnrollmentToLead, AbsentStudentsList, UpdateEnrollmentAbsentNote

# API
from .views import StudentListView
app_name = 'students'

urlpatterns = [
    path('student/<int:pk>', StudentUpdateView.as_view(), name='student_update'),
    path('create_student', CreateStudentView.as_view(), name='create_student'),
    path('enrollment/<int:pk>/', UpdateEnrollmentView.as_view(), name='update_enrollment'),
    path('enrollment/create/', CreateEnrollmentView.as_view(), name='create_enrollment'),
    path('enrollment/delete/<int:enrollment_id>', DeactivateEnrollmentView.as_view(), name='delete_enrollment'),
    path('enrollment/create/course/<int:course_id>/', CreateEnrollmentView.as_view(), name='create_enrollment_from_course'),
    path('enrollment/create/student/<int:student_id>/', CreateEnrollmentView.as_view(), name='create_enrollment_from_student'),
    path('enrollment/update-note/<int:pk>/', UpdateEnrollmentNote.as_view(), name='update_enrollment_note'),
    path('enrollment/update-absent-note/<int:pk>/', UpdateEnrollmentAbsentNote.as_view(), name='update_enrollment_absent_note'),
    path('enrollment/re-enroll/<int:pk>', ReEnrollStudentView.as_view(), name='re_enroll'),
    path('enrollment/group-re-enroll/<int:group_id>', GroupReEnrollmentView.as_view(), name="group-re-enroll"),
    path('autocomplete-students/', autocomplete_students, name='autocomplete-students'),
    path('student/<int:pk>/archive', ArchiveStudent.as_view(), name='archive_student'),
    path('student/<int:pk>/unarchive', UnArchiveStudent.as_view(), name='unarchive_student'),
    path('student/<int:enrollment_id>/convert-lead', ConvertEnrollmentToLead.as_view(), name='convert_enrollment_to_lead'),
    path('student/absent-list', AbsentStudentsList.as_view(), name='absent_list'),

    # Api

    path('api/students-list/', StudentListView.as_view(), name='api-student-list'),
]

leads/models.py
from django.db import models

from students.models import StudentModel, Enrollment
from users.models import UsersModel
from courses.models import SubjectModel

class LeadsModel(models.Model):
    student = models.ForeignKey(StudentModel, on_delete=models.CASCADE, verbose_name="Ученик")
    weekdays = models.IntegerField(choices=[(1, "Нечетные"), (2, "Четные"), (3, "Другие")], null=True, blank=True, verbose_name="Дни уроков")
    lesson_time = models.TimeField(verbose_name="время урока", null=True, blank=True)
    subject = models.ForeignKey(SubjectModel, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Предмет")
    teacher = models.ForeignKey(UsersModel, on_delete=models.SET_NULL, null=True, blank=True, limit_choices_to={'role': '1', 'is_active': True}, verbose_name="учитель")
    arrival_date = models.DateField(null=True, blank=True, verbose_name="Примерная дата")
    note = models.TextField(null=True, blank=True, max_length=500, verbose_name="Заметка")
    status = models.IntegerField(choices=[(1, "Ожидание"), (2, "Обработан"), (3, "Отменен")], default=1)
    enrollment_result = models.ForeignKey(Enrollment, on_delete=models.SET_NULL, null=True, blank=True)
    created_by = models.ForeignKey(UsersModel, on_delete=models.SET_NULL, null=True, blank=True, related_name='created_by')
    processed_by = models.ForeignKey(UsersModel, on_delete=models.SET_NULL, null=True, blank=True, related_name='processed_by')
    processed_at = models.DateTimeField(null=True, blank=True)

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'лид'
        verbose_name_plural = 'лиды'

payment/models.py
from django.db import models
from students.models import Enrollment


class PaymentModel(models.Model):
    enrollment = models.ForeignKey(Enrollment, on_delete=models.CASCADE, verbose_name="Запись")
    months = models.PositiveIntegerField(verbose_name="Кол-во месяйев")
    payed_lessons = models.PositiveIntegerField(null=True)
    amount = models.FloatField(null=True, blank=True, verbose_name="Сумма оплаты")
    payed_from = models.DateField(null=True, blank=True, verbose_name="Начало абонимента")
    payed_due = models.DateField(null=True, blank=True, verbose_name="Конец абонимента")
    manual_dates = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True, verbose_name="Дата и время оплаты")
    payment_type = models.IntegerField(choices=[(1, 'Наличные'), (2, 'Карта'), (3, "Онлайн перевод")], default=1, verbose_name='Тип оплаты')

    def __str__(self):
        return f"{self.enrollment.student} - {self.enrollment.course.subject}, {self.enrollment.course}"

    class Meta:
        verbose_name = "оплата"
        verbose_name_plural = "оплаты"

payment/views.py
from calendar import month
from datetime import datetime, timedelta, time, timezone

from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import View, ListView, UpdateView
from django.db.models import Q
from courses.models import CourseModel
from users.filters import AdminRequired, SuperUserRequired
from users.helpers import record_action
from users.models import UsersModel
from .models import PaymentModel
from .forms import CreatePaymentForm, PaymentHistoryFilterForm, UpdatePaymentDatesForm, TrialStudentsFilterForm
from students.models import Enrollment, StudentModel
from .helpers import calculate_payment_due_date, calculate_payment_amount, next_closest_session_date
from collections import defaultdict
from django.urls import reverse
from urllib.parse import urlencode
import traceback

class PaymentsListView(AdminRequired, ListView):
    model = PaymentModel
    template_name = 'payment/payments_list.html'
    context_object_name = 'payments'
    ordering = ['-id']
    paginate_by = 50

    def get(self, request, *args, **kwargs):
        # If no filters provided, but session has saved filters — redirect with them
        if not request.GET and request.session.get("payments_filters"):
            return redirect(f"{reverse('payment:payments_list')}?{urlencode(request.session['payments_filters'])}")

        # If GET has filters, store them
        if request.GET:
            request.session["payments_filters"] = request.GET.dict()

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        data = self.request.GET.copy()
        teacher_id = data.get('teacher')
        course_id = data.get('course')
        student_id = data.get('student')

        context['filter_form'] = PaymentHistoryFilterForm(initial=data, teacher_id=teacher_id, course_id=course_id, student_id=student_id)
        context['queryset_length'] = self.get_queryset().count()
        context['today'] = datetime.now().date()
        return context

    def get_queryset(self):
        queryset = PaymentModel.objects.all()
        teacher = self.request.GET.get('teacher', None)
        course = self.request.GET.get('course', None)
        student_id = self.request.GET.get('student', None)
        sort_by = self.request.GET.get('sort_by', None)
        payment_date_start = self.request.GET.get('payment_date_start', None)
        payment_date_end = self.request.GET.get('payment_date_end', None)

        if student_id:
            queryset = queryset.filter(enrollment__student_id=student_id)

            if course:
                courses = CourseModel.objects.filter(enrollment__student_id=student_id).values_list('id', flat=True)
                if str(course) in str(courses):
                    queryset = queryset.filter(enrollment__course=course)

        if course and not student_id:
            queryset = queryset.filter(enrollment__course=course)
            if teacher:
                course = get_object_or_404(CourseModel, id=course)
                if course.teacher.id == teacher:
                    queryset = queryset.filter(enrollment__course__teacher=teacher)

        if teacher and not course:
            queryset = queryset.filter(enrollment__course__teacher=teacher)

        if payment_date_start:
            queryset = queryset.filter(date__gt=payment_date_start)

        if payment_date_end:
            end_date = datetime.strptime(payment_date_end, '%Y-%m-%d')
            queryset = queryset.filter(date__lte=end_date+timedelta(days=1))

        if sort_by:
            if sort_by == '1':
                queryset = queryset.order_by('-id')
            elif sort_by == '2':
                queryset = queryset.order_by('id')
            elif sort_by == '3':
                queryset = queryset.filter(enrollment__status=False).order_by('-id')
            elif sort_by == '4':
                queryset = queryset.order_by('-months')
        else:
            queryset = queryset.order_by('-id')

        return queryset


class CreatePaymentView(AdminRequired, View):
    def post(self, request, enrollment_id):
        enrollment = get_object_or_404(Enrollment, id=enrollment_id)
        form = CreatePaymentForm(request.POST)
        next_url = request.GET.get('next', '/')

        if self.request.user.is_superuser or 'create_payment' in request.user.custom_permissions:
            if form.is_valid():

                months = form.cleaned_data['months']
                auto_date = form.cleaned_data['automatic_date']
                start_date = form.cleaned_data.get('start_date')
                end_date = form.cleaned_data.get('end_date')
                lessons_count = form.cleaned_data.get('lessons_count')
                payment_type = form.cleaned_data.get('payment_type')

                try:
                    payment = PaymentModel.objects.create(enrollment=enrollment, months=months, payment_type=payment_type)

                    payed_lessons = 0
                    if int(months) == 0:
                        if int(lessons_count) > 0:
                            payed_lessons = int(lessons_count)
                    else:
                        payed_lessons = 12 * int(months)

                    payment.payed_lessons = payed_lessons
                    payment.amount = calculate_payment_amount(enrollment, payed_lessons)


                    # Determine payed_from and payed_due
                    if auto_date:
                        base_date = enrollment.payment_due if enrollment.payment_due else datetime.today().date()
                        payment.payed_from = next_closest_session_date(course=enrollment.course, today=base_date, include_today=True if not enrollment.payment_due else False)
                        payment.payed_due = calculate_payment_due_date(enrollment, payed_lessons, payment.payed_from)
                    else:
                        payment.payed_from = start_date if start_date else datetime.today()
                        payment.payed_due = end_date or calculate_payment_due_date(enrollment, payed_lessons, payment.payed_from)
                        payment.manual_dates = True

                    payment.save()

                    # Update enrollment's payment_due if necessary
                    if enrollment.payment_due is None:
                            enrollment.payment_due = payment.payed_due
                    else:
                        if enrollment.payment_due < payment.payed_due:
                            enrollment.payment_due = payment.payed_due

                    enrollment.save()

                    # Record action
                    action_message = f"Оплата ученика <b>{payment.enrollment.student}</b> в группу <b>{payment.enrollment.course}</b>"
                    record_action(1, request.user, payment, payment.id, action_message)

                    messages.success(request, "Оплата успешно добавлена.")
                except Exception as e:
                    messages.error(request, "Что-то пошло не так.")
                    traceback.print_exc()

            else:
                messages.success(request, "Ошибка в форме")
        else:
            messages.warning(request, 'У вас не доступа к этой функции')

        return redirect(next_url)


class DebtPaymentsListView(AdminRequired, View):
    template_name = 'payment/debt_payments_list.html'

    def get(self, request):
        # If no filters provided, but session has saved filters — redirect with them
        if not request.GET and request.session.get("debts_filters"):
            return redirect(f"{reverse('payment:debt_payments_list')}?{urlencode(request.session['debts_filters'])}")

        # If GET has filters, store them
        if request.GET:
            request.session["debts_filters"] = request.GET.dict()


        teachers = UsersModel.objects.filter(role='1').distinct()
        # Filters
        weekdays = self.request.GET.get('weekdays', None)

        enrollments = Enrollment.objects.select_related('course__teacher').filter(Q(payment_due__lt=datetime.today().date()), payment_due__isnull=False, status=True).order_by('course__teacher__first_name', 'course__teacher__last_name','course__lesson_time', 'student__first_name', 'student__last_name')

        if weekdays:
            if weekdays == '1':
                enrollments = enrollments.filter(course__weekdays__contains='0,2,4')
            elif weekdays == '2':
                enrollments = enrollments.filter(course__weekdays__contains='1,3,5')
            else:
                enrollments = enrollments.exclude(
                    Q(course__weekdays__contains='0,2,4') | Q(course__weekdays__contains='1,3,5'))

        course_enrollment_map = defaultdict(list)
        for enrollment in enrollments:
            course = enrollment.course
            course_enrollment_map[course].append(enrollment)

        teacher_data = defaultdict(lambda: defaultdict(list))
        for course, enrollment_list in course_enrollment_map.items():
            teacher = course.teacher
            teacher_data[teacher][course] = enrollment_list

        teacher_data = {
            teacher: dict(course_map)
            for teacher, course_map in teacher_data.items()
        }

        context = {'teacher_enrollments': teacher_data}
        context['filter_form'] = TrialStudentsFilterForm(initial=self.request.GET)
        return render(request, self.template_name, context)

class TrialEnrollmentsView(AdminRequired, View):
    template_name = 'payment/trial_students_list.html'

    def get(self, request):
        # If no filters provided, but session has saved filters — redirect with them
        if not request.GET and request.session.get("trials_filters"):

templates/payment/absent_students_list.html
{% extends 'layout/base.html' %}

{% block title %}
    <title>Панель Управления</title>
{% endblock %}
{% block content %}
    {% include 'layout/navbar.html' %}

    <div class="container courses-list">
        <div class="mt-5 mb-2 d-flex align-items-center justify-content-between">
        </div>
        {% include './payments_page_navbar.html' %}
        <hr class="table-group-divider mt-0"/>

        <div class="d-flex flex-column flex-md-row mb-3">
            <div class="bg-light bg-light rounded py-2 px-2 border">
                <form method="get">
                    <div class="mb-3">
                        <h6 class="text-dark ms-1 fs-6 m-0">Просмотр по дате
                            <a href="?date={{ today }}" type="reset" class="filter-reset-btn ms-2 mb-1"><p>
                                Сбросить</p></a>
                        </h6>
                    </div>
                    <div class="d-flex gap-2">

                        <a href="?date={{ prev_date|date:"Y-m-d" }}" class="btn btn-outline-primary"><i
                                class="bi bi-caret-left-fill"></i></a>
                        <input type="date" name="date" max="{{ today }}" value="{{ filter_date }}"
                               class="form-control border-primary" onchange="this.form.submit()">
                        <a href="?date={{ next_date|date:"Y-m-d" }}"
                           class="btn btn-outline-primary {% if filter_date == today %} disabled{% endif %}"><i
                                class="bi bi-caret-right-fill"></i></a>
                    </div>
                </form>
            </div>
        </div>
        <div class="row px-3 mt-3 debt-accordions">

            {% for teacher, courses in teacher_enrollments.items %}
                <ol class="list-group my-2 border-primary border p-0">
                    <li class="list-group-item list-group-item-primary w-100 fs-5 fw-semibold mb-3">{{ forloop.counter }}. {{ teacher }}</li>
                    {% for course, enrollments in courses.items %}
                        <li class="list-unstyled list-group-item border-0 py-0 mb-3">

                            <ul class="list-group border border-secondary shadow shadow-sm"
                                id="courseTable{{ course.id }}">
                                <li class="list-group-item-secondary list-group-item fw-semibold bg-opacity-25">
                                    <a href="{% url 'courses:course_update' pk=course.course.id %}"
                                       class="my-auto text-dark table-obj-name-link text-decoration-none">{{ course }}</a>
                                </li>
                                {% for attendance in enrollments %}
                                    <li class="list-group-item d-flex justify-content-between align-items-center list-items-hover">
                                        <div class="d-flex">
                                            <span class="text-secondary me-1">{{ forloop.counter }}.</span> <a
                                                href="{% url 'students:student_update' pk=attendance.enrollment.student.id %}"
                                                class="my-auto text-dark table-obj-name-link text-decoration-none">{{ attendance.enrollment.student.full_name }}</a>
                                            <p class="m-0 ms-2  {% if attendance.status == 0 %}text-danger {% else %}text-secondary {% endif %}">
                                                - {{ attendance.get_status_display|default:"?" }}</p>
                                        </div>
                                        <div class="debt-students-phone-numbers d-flex align-items-center gap-3">
                                            <span type="button" copy="{{ attendance.enrollment.student.phone_number }}"
                                                  onclick="navigator.clipboard.writeText(this.getAttribute('copy')), this.classList.add('copied'), setTimeout(()=>{this.classList.remove('copied')}, 1000)">{{ attendance.enrollment.student.phone_number }}</span>
                                            <span type="button"
                                                  copy="{{ attendance.enrollment.student.additional_number|default_if_none:"---" }}"
                                                  {% if enrollment.student.additional_number %}onclick="navigator.clipboard.writeText(this.getAttribute('copy')), this.classList.add('copied'), setTimeout(()=>{this.classList.remove('copied')}, 1000)"{% endif %}>{{ attendance.enrollment.student.additional_number|default_if_none:"---" }}</span>
                                            <div class="w-350px">
                                                <form method="post" onsubmit="handleFormSubmit(event)" class="w-350px noBtn note-update-form"
                                                  action="{% url 'students:update_enrollment_absent_note' pk=attendance.enrollment.id %}">
                                                {% csrf_token %}
                                                <input name="text" onchange="this.form.requestSubmit()" maxlength="40"
                                                       class="text-center form-control rounded-0 align-middle w-100"
                                                       value="{{ attendance.enrollment.absent_note|default:'' }}">
                                            </form>
                                            </div>
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ol>
            {% empty %}
                <p class="text-center text-secondary">Пусто.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/payment/create_payment.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  <title>Панель Управления</title>
{% endblock %}
{% block content %}
  {% include 'layout/navbar.html' %}

  <div class="container courses-list">

    <h4 class="mt-5">Создать информацию об оплате</h4>
    <hr class="table-group-divider" />
    <form method="post">
      {% csrf_token %}
      {{form|crispy}}
      <div class="d-flex justify-content-end flex-column flex-md-row pt-3">
        <button type="submit" class="btn btn-primary">Сохранить</button>
      </div>
    </form>
  </div>
{% endblock %}

templates/payment/payments_page_navbar.html
<div class="">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            {% url 'payment:debt_payments_list' as cpath %}
            <a class="nav-link {% if request.path == cpath %}active{% endif %}"
               href="{% url 'payment:debt_payments_list' %}">Должники</a>
        </li>
        <li class="nav-item">
            {% url 'payment:trial_enrollments_list' as cpath %}
            <a class="nav-link {% if request.path == cpath %}active{% endif %}"
               href="{% url 'payment:trial_enrollments_list' %}">Пробники</a>
        </li>
        <li class="nav-item">
            {% url 'payment:payments_list' as cpath %}
            <a class="nav-link {% if request.path == cpath %}active{% endif %}"
               href="{% url 'payment:payments_list' %}">История оплат</a>
        </li>
        <li class="nav-item">
            {% url 'students:absent_list' as cpath %}
            <a class="nav-link {% if request.path == cpath %}active{% endif %}"
               href="{% url 'students:absent_list' %}">Отсутсвие</a>
        </li>
    </ul>
</div>

templates/payment/update_dates.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    <title>Панель Управления</title>
{% endblock %}
{% block content %}
    {% include 'layout/navbar.html' %}

    <div class="container courses-list">

        <h4 class="mt-5">Обновить даты оплаты</h4>
        <hr class="table-group-divider"/>
        <div class="col-12 bg-light rounded p-3 border">
            <form method="post">
                {% csrf_token %}
                <p><b>Ученик:</b> {{ object.enrollment.student.full_name }}</p>
                <p><b>Курс:</b> {{ object.enrollment.course }}</p>
                <p><b>Начало:</b> {{ object.payed_from }}</p>
                <p><b>Конец:</b> {{ object.payed_due }}</p>
                <p><b>Дата оплаты:</b> {{ object.date }}</p>
                {{ form|crispy }}

                <div class="d-flex justify-content-end flex-column flex-md-row pt-3">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block custom_js %}

    <script>
    function custom_due_date_toggle(check){
        console.log(check.checked)
        let div = document.getElementById('div_id_payed_due')

        if (check.checked == true){
            div.classList.add('d-none')
        }else{
            div.classList.remove('d-none')
        }
    }
    </script>

{% endblock %}

templates/payment/view_payment.html
{% extends 'layout/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  <title>Панель Управления</title>
{% endblock %}
{% block content %}
  {% include 'layout/navbar.html' %}

  <div class="container courses-list">
    <h4 class="mt-5">Чек</h4>
    <hr class="table-group-divider" />

    <form method='post'>
        {% csrf_token %}
        {{form|crispy}}


      {% if not form.status.value %}
      <div class="alert alert-danger d-flex justify-content-between flex-column align-items-center flex-md-row pt-3 gap-3">
        <p class="m-0">Этот чек не оплачен!</p>
          <button type="submit" name='confirm' class="btn btn-success">Оплачено</button>
      </div>
      {% endif %}
    </form>
  </div>
{% endblock %}