api/urls.py
from collections import UserList
from django.urls import path, include
from .views import UserProfileView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/users/profile/', UserProfileView.as_view(), name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'), name='users'),
    path('', include('main.urls'), name='main'),
    path('', include('attendance.urls'), name='attendance'),
    path('', include('students.urls'), name='students'),
    path('', include('courses.urls'), name='courses'),
    path('', include('payment.urls'), name='payment'),
    path('', include('leads.urls'), name='leads'),
    path('', include('analytics.urls'), name='analytics'),

    path('api-auth/', include('rest_framework.urls')),
    # path('', include('api.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import MainPageView, StudentsListView,   TeachersListView, CoursesListView, EnrollmentsListView

app_name = 'main'

urlpatterns = [
    # path('', MainPageView.as_view(), name='main'),
    # path('students', StudentsListView.as_view(), name='students_list'),
    # path('teachers/', TeachersListView.as_view(), name='teachers_list'),
    # path('courses/', CoursesListView.as_view(), name='courses_list'),
    # path('enrollments/', EnrollmentsListView.as_view(), name='enrollments_list'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy

from .views import CustomUserCreateView, reset_user_password, UserUpdateView, LoginPageView, ProfileView, TeacherUpdateView, CustomPasswordChangeView, SalaryUsersListView, SalaryCourseDetailView, AdminActionsView, UsersListView

# Api
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import UserProfileView
app_name = 'users'

urlpatterns = [
    path('login/', LoginPageView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('home')), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('teacher/<int:pk>', TeacherUpdateView.as_view(), name='teacher_update'),
    path('profile/password-change/', CustomPasswordChangeView.as_view(), name='update_password'),
    path('actions-history/', AdminActionsView.as_view(), name='admin_actions'),

    path('users/', UsersListView.as_view(), name='users_list'),
    path('users/<int:pk>/update/', UserUpdateView.as_view(), name='user_update'),
    path('users/<int:pk>/reset-password/', reset_user_password, name='reset_user_password'),
    path('users/create/', CustomUserCreateView.as_view(), name='user_create'),
    path('salary/users/', SalaryUsersListView.as_view(), name='salary_users_list'),
    path('salary/teacher/<int:teacher_id>/course/<int:course_id>', SalaryCourseDetailView.as_view(), name='salary_course_detail'),


    #     API
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/users/profile/', UserProfileView.as_view(), name='user-profile'),
]

templates/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    {% block title %}
        <title>Title</title>
    {% endblock %}
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/main.css' %}"/>
    <link rel="stylesheet" href="{% static 'packages/flatpickr/flatpickr.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'packages/bootstrap-icons/font/bootstrap-icons.min.css' %}"/>
    <!-- Select 2 -->
    <link rel="stylesheet" href="{% static 'packages/select2/select2.min.css' %}"
          integrity="sha512-yI2XOLiLTQtFA9IYePU0Q1Wt0Mjm/UkmlKMy4TU4oNXEws0LybqbifbO8t9rEIU65qdmtomQEQ+b3XfLfCzNaw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    {% block custom_css %}

    {% endblock %}
</head>
<body>
<div class="pb-5">

        <div id="message-container" class="position-fixed top-0 start-50 translate-middle-x pt-2" style="z-index: 1055;">
         {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} p-1 mb-2 ps-3 d-flex align-items-center alert-dismissible fade show" role="alert">
              <span>{{ message }}</span>
            <button type="button" class="btn-close position-relative p-2 ms-4 shadow-none" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
        {% endif %}
        </div>

    {% block content %}

    {% endblock %}
</div>
<script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}" defer></script>
<script src="{% static 'packages/jquery/jquery.min.js' %}"></script>
<script src="{% static 'packages/flatpickr/flatpickr.js' %}"></script>
<!-- Select2 -->
<script src="{% static 'packages/select2/select2.min.js' %}"
        integrity="sha512-qiKM6FJbI5x5+GL5CEbAUK0suRhjXVMRXnH/XQJaaQ6iQPf05XxbFBE4jS6VJzPGIRg7xREZTrGJIZVk1MLclA=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="{% static 'js/main.js' %}"></script>
<script>
  window.addEventListener('DOMContentLoaded', () => {
    const alerts = document.querySelectorAll('#message-container .alert');
    alerts.forEach((alert) => {
      setTimeout(() => {
        const bsAlert = bootstrap.Alert.getOrCreateInstance(alert);
        bsAlert.close();
      }, 4000); // 4000 ms = 4 seconds
    });
  });
</script>

{% block custom_js %}

{% endblock %}
</body>
</html>

templates/layout/navbar.html
{% load static %}

<nav class="navbar nav-underline navbar-expand-lg py-0 border border-2">
    <div class="container py-0">
        <a class="navbar-brand py-0" href="{% url 'main:main' %}"><img src="{% static 'img/logo.png' %}" alt=""/></a>
        {#    <a href="{% url 'users:profile' %}" class="profile-navbtn d-block d-lg-none ms-auto me-4"><img src="{% static 'img/user.webp' %}" alt="" /></a>#}

        <div class="d-flex align-items-center gap-3">

            <div class="d-block d-lg-none">
                <ul class="list-unstyled my-auto">
                    <li class="dropdown-center">
                        <a class="nav-link dropdown-toggle {% if request.path|slice:9 == '/profile/' %}active{% endif %}"
                           href="#"
                           role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <ul class="dropdown-menu-end dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'users:update_password' %}">Пароль</a></li>
                            {% if request.user.is_superuser %}
                                <li><a class="dropdown-item" href="{% url 'users:users_list' %}">Пользователи</a></li>
                                <li><a class="dropdown-item" href="{% url 'users:admin_actions' %}">История</a></li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <form class="" method="post" action="{% url 'users:logout' %}">{% csrf_token %}
                                    <button class="dropdown-item text-danger" type="submit">Выйти</button>
                                </form>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
        </div>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto text-center mb-2 pb-2 mb-lg-0 gap-2">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page"
                       href="{% url 'main:main' %}">Сегодня</a>
                </li>
                {% if user.role == '1' %}
                    {% url 'courses:mygroups' as cpath %}
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == cpath %}active{% endif %}" aria-current="page"
                           href="{% url 'courses:mygroups' %}">Посещаемость</a>
                    </li>
                {% endif %}
                {% if user.role == '2' %}
                    <li class="nav-item">
                        {% url 'main:courses_list' as cpath %}
                        <a class="nav-link {% if request.path == cpath %}active{% endif %}" aria-current="page"
                           href="{% url 'main:courses_list' %}">Группы</a>
                    </li>
                    <li class="nav-item">
                        {% url 'main:students_list' as cpath %}
                        <a class="nav-link {% if request.path == cpath %}active{% endif %}" aria-current="page"
                           href="{% url 'main:students_list' %}">Ученики</a>
                    </li>
                    <li class="nav-item">
                        {% url 'main:enrollments_list' as cpath %}
                        <a class="nav-link {% if request.path == cpath %}active{% endif %}" aria-current="page"
                           href="{% url 'main:enrollments_list' %}">Записи</a>
                    </li>
                    <li class="nav-item">
                        {% url 'main:teachers_list' as cpath %}
                        <a class="nav-link {% if request.path == cpath %}active{% endif %}" aria-current="page"
                           href="{% url 'main:teachers_list' %}">Учителя</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path|slice:':9' == '/payments' %}active{% endif %}"
                           aria-current="page" href="{% url 'payment:payments_list' %}">Оплаты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if request.path|slice:':6' == '/leads' %}active{% endif %}"
                           aria-current="page" href="{% url 'leads:leads_list' %}">Лиды</a>
                    </li>
                    {% if user.is_superuser %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path|slice:':7' == '/salary' %}active{% endif %}"
                               aria-current="page" href="{% url 'users:salary_users_list' %}">Зарплата</a>
                        </li>
                        <li class="nav-item">
                            {% url 'analytics:analytics_page' as cpath %}
                            <a class="nav-link {% if request.path == cpath %}active{% endif %}"
                               aria-current="page" href="{% url 'analytics:analytics_page' %}">Аналитика</a>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
        </div>

        <div class="d-none d-lg-block">
            <ul class="list-unstyled my-auto">
                <li class="dropdown-center">
                    <a class="nav-link dropdown-toggle {% if request.path|slice:9 == '/profile/' %}active{% endif %}"
                       href="#"
                       role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu-end dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'users:update_password' %}">Пароль</a></li>
                        {% if request.user.is_superuser %}
                            <li><a class="dropdown-item" href="{% url 'users:users_list' %}">Пользователи</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:admin_actions' %}">История</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <form class="" method="post" action="{% url 'users:logout' %}">{% csrf_token %}
                                <button class="dropdown-item text-danger" type="submit">Выйти</button>
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/layout/pagination.html
<div class="row mt-5">
    <div class="col-12 col-lg-8 offset-lg-2 d-flex justify-content-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination ">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page=1"
                           aria-label="Previous">
                            <span aria-hidden="true"><i class="bi bi-chevron-double-left"></i></span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.previous_page_number }}"
                           aria-label="Previous">
                            <span aria-hidden="true"><i class="bi bi-chevron-left"></i></span>
                        </a>
                    </li>
                {% endif %}
                {% for page in paginator.page_range %}
                    {% if page_obj.number == page %}
                        <li class="page-item ms-1"><a class="page-link active"
                                                      href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page }}">{{ page }}</a>
                        </li>
                    {% elif page > page_obj.number|add:-4 and page < page_obj.number|add:4 %}
                        <li class="page-item ms-1"><a class="page-link"
                                                      href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page }}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item ms-1">
                        <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.next_page_number }}"
                           aria-label="Next">
                            <span aria-hidden="true"><i class="bi bi-chevron-double-right"></i></span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?{% for key, value in request.GET.items %}{% if key != 'page' %}{{ key }}={{ value }}&{% endif %}{% endfor %}page={{ page_obj.paginator.num_pages }}"
                           aria-label="Next">
                            <span aria-hidden="true"><i class="bi bi-chevron-double-right"></i></span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>